name: example
publish_to: none
description: >
  Just an example, not for publishing.
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  built_collection:
    git:
      url: https://github.com/JonHodgson/built_collection.dart.git
      ref: master
  built_value: ^8.0.0

dev_dependencies:
  build_runner: ^2.1.2
  built_value_generator: ^8.1.2
  pedantic: ^1.4.0
  quiver: '>=0.21.0 <4.0.0'
  test: ^1.0.0

dependency_overrides:
  built_value:
    path: ../built_value
  built_value_generator:
    path: ../built_value_generator
  built_collection:
    git:
      url: https://github.com/JonHodgson/built_collection.dart.git
      ref: master
