name: built_value
version: 8.1.2
publish_to: none
description: >
  Value types with builders, Dart classes as enums, and serialization.
  This library is the runtime dependency.
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  built_collection: any
  collection: ^1.15.0
  fixnum: ^1.0.0
  meta: ^1.3.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0

dependency_overrides:
  built_value_generator:
    git:
      url: https://github.com/JonHodgson/built_value.dart.git
      path: built_value_generator
      ref: master
  built_collection:
    git:
      url: https://github.com/JonHodgson/built_collection.dart.git
      ref: master

