name: built_value_analyzer_plugin_loader
version: 8.1.2
description: This pubspec determines the version of the analyzer plugin to load.
environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
built_value_analyzer_plugin: ^8.1.2
built_value_generator: ^8.1.2
dependency_overrides:
  built_value_analyzer_plugin:
    path: ../../../built_value_analyzer_plugin
  built_value_generator:
    path: ../../../built_value_generator

