name: built_value_analyzer_plugin
version: 8.1.2
description: >
  Experimental analyzer plugin for the built_value code generator.
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  analyzer: '>=1.8.0 <3.0.0'
  analyzer_plugin: ^0.7.0
  built_value: ^8.1.2
  built_value_generator: ^8.1.2

dev_dependencies:
  build_test: ^2.1.3
  pedantic: ^1.4.0
  test: ^1.0.0

dependency_overrides:
  built_value:
    git:
      url: https://github.com/JonHodgson/built_value.dart.git
      path: built_value
      ref: master
  built_value_generator:
    git:
      url: https://github.com/JonHodgson/built_value.dart.git
      path: built_value_generator
      ref: master

